name: CI/CD Next.js Portfolio

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd kornshportfolio && npm ci

      - name: Build Next.js app
        run: cd kornshportfolio && npm run build -- --no-lint

      - name: Export static site (if needed)
        run: |
          cd kornshportfolio
          if grep -q 'output:.*export' next.config.ts; then
            npm run export
          fi

      - name: Upload production-ready build
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: kornshportfolio/.next

      # Déploiement automatique (exemple avec Vercel CLI, à adapter selon cible)
      # - name: Deploy to Vercel
      #   run: cd kornshportfolio && npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
