name: Coverage & Codecov

on:
  push:

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd kornshportfolio && npm ci

      - name: Run tests (Vitest JUnit)
        run: cd kornshportfolio && npm run test:ci

      - name: Upload JUnit test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: kornshportfolio/test-report.junit.xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ujju16/kornshdevportfolio
          directory: ./kornshportfolio/coverage
